#PV를 생성할하래HostPath를 777로 설정
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nexus-data
  labels:
    type: local
spec:
  storageClassName: nexus
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/pvc/nexus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nexus-data
spec:
  storageClassName: nexus
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
