kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nexus-data
  labels:
    type: local
spec:
  storageClassName: nexus
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/pvc/nexus-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nexus-data
spec:
  storageClassName: nexus
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
