kind: PersistentVolume
apiVersion: v1
metadata:
  name: nexus-data
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  reclaimPolicy:
    - Recycle
  hostPath:
    path: "/pvc/nexus-data"
